### PR TITLE
thunkLang

### PR DESCRIPTION
**Pull request by oskarabrahamsson**

### CODE REVIEW

**Comment by myreen** [comment]
Looks good and clean!

I notice that Force is introduced in two rules `exp_rel_App` and `exp_rel_Proj`, which I wonder whether we could have special cases for situations when a `Force` can be avoided. 
```
[exp_rel_App_Var:]
  (∀f g x y.
     exp_rel f g ∧
     exp_rel x y ⇒
       exp_rel (App f (Tick (Var v))) (App g (Var v))) ∧
```

```
[exp_rel_Let_Proj:]
  (∀s i xs ys.
     LIST_REL exp_rel xs ys ∧
     exp_rel x y ⇒
       exp_rel (Let v (Prim (Proj s i) xs) x) (Let v (Prim (Proj s i) ys) y)) ∧
```

**Comment by myreen** [comment]
(Oops, I pressed "Comment" too soon.) 

I just want to add that I suspect `exp_rel_App_Var` is a fairly common pattern. 

`Let v (Prim (Proj s i) xs) x` is not as common, but does occur in the way I envision `Case` will be expanded. 

If we don't have these rules, then I believe the code will contain `Delay (Force _)` which I suspect is difficult to compile away with a later optimisation. (In contrast to `Force (Delay _))` which is easy to optimise away.)

**Comment by oskarabrahamsson** [comment]
It looks as if `exp_rel_Let_Proj` will fit in with the existing relation. `exp_rel_App_Var` will not fit, because at present we always allocate a thunk when a variable is bound.

**Comment by oskarabrahamsson** [comment]
This is starting to get quite big, so I'm going to merge this PR into master now.

Here's what has happened since the last discussion:
- There's a pass that replaces `Delay (Force (Var v))` with `Var v` (thunk_subst_unthunk)
- Hrutvik has implemented a top-level semantics for thunkLang, as well as cexps

Here's what's still needs to be done with thunkLang:
- Implement the LetProj-removal discussed further up in this thread
- Prove a `eval` theorem for the thunk_subst_unthunk pass (there's something about `eval_to` currently)
- Compose all pureLang and thunkLang exp_rel's into something that can be used for a pass which compiles pureLang to the env-based thunkLang.

**Pull request merged**
